# Generated by Django 3.0 on 2020-04-13 20:39

import auctions.models.AuctionStatus
import auctions.models.Currency
import auctions.models.ItemCondition
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_ask_amount', models.FloatField(default=0)),
                ('expiration_time_utc', models.DateTimeField()),
                ('international_delivery', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auction',
            },
        ),
        migrations.CreateModel(
            name='AuctionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(choices=[(auctions.models.AuctionStatus.AuctionStatusOption['OPEN'], 'open'), (auctions.models.AuctionStatus.AuctionStatusOption['CLOSED'], 'closed'), (auctions.models.AuctionStatus.AuctionStatusOption['FULFILLED'], 'fulfilled')], max_length=20, unique=True)),
            ],
            options={
                'db_table': 'auction_status',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.FloatField()),
                ('bid_time_utc', models.DateTimeField()),
                ('is_winning_bid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bid',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(choices=[(auctions.models.Currency.CurrencyOptions['USD'], 'usd'), (auctions.models.Currency.CurrencyOptions['GBP'], 'gbp')], max_length=5, unique=True)),
            ],
            options={
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='ItemCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(choices=[(auctions.models.ItemCondition.ItemConditionOptions['NEW'], 'new'), (auctions.models.ItemCondition.ItemConditionOptions['USED'], 'used')], max_length=20, unique=True)),
            ],
            options={
                'db_table': 'item_condition',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=125)),
                ('description', models.TextField(max_length=5000)),
                ('registration_date_utc', models.DateTimeField(default=django.utils.timezone.now)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.ItemCondition')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
