# Generated by Django 3.0 on 2020-04-13 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.Auction'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.Currency'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auction',
            name='ask_amount_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.Currency'),
        ),
        migrations.AddField(
            model_name='auction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.Item'),
        ),
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.AuctionStatus'),
        ),
    ]
