# Generated by Django 3.0 on 2020-04-11 22:25

from django.db import migrations


def add_currencies(apps, schema):
    Model = apps.get_model('auctions', 'Currency')
    for curr in ['usd', 'gbp']:
        c = Model()
        c.value = curr
        c.save()


def add_auction_statuses(apps, schema):
    Model = apps.get_model('auctions', 'AuctionStatus')
    for curr in ['open', 'closed', 'fulfilled']:
        c = Model()
        c.value = curr
        c.save()


def add_conditions(apps, schema):
    Model = apps.get_model('auctions', 'ItemCondition')
    for curr in ['new', 'used']:
        c = Model()
        c.value = curr
        c.save()


def add_countries(apps, schema):
    countries = ['United States', 'United Kingdom']
    Country = apps.get_model('auctions', 'Country')
    for country in countries:
        c = Country()
        c.name = country
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200413_2039'),
    ]

    operations = [
        migrations.RunPython(add_currencies),
        migrations.RunPython(add_conditions),
        migrations.RunPython(add_auction_statuses),
        migrations.RunPython(add_countries),
    ]